import {ITour} from "./itour"

export const MockTourData : ITour[] = [
        {
            id: 0,
            name: "Beautiful Paris",
            destination: "Paris",
            country:"France",
            dateStart: new Date(2021, 4, 4),
            dateEnd: new Date(2021, 4, 14),
            price: 1222,
            description:"Paris' monument-lined boulevards, museums, classical bistros and boutiques are enhanced by a new wave of multimedia galleries, creative wine bars, design shops and tech start-ups.",
            image: "https://picsum.photos/id/318/768/768",
            availablePlaces: 12,
            totalPlaces: 12,
            rating: 0,
            totalVotes: 0
        },
        {
            id: 1,
            name: "Discover Stockholm",
            destination: "Stockholm",
            country:"Sweden",
            dateStart: new Date(2021, 12, 24),
            dateEnd: new Date(2021, 12, 25),
            price: 1422,
            description:"Stockholmers call their city 'beauty on water'. But despite the well-preserved historic core, Stockholm is no museum piece: it's modern, dynamic and ever-evolving.",
            image: "https://picsum.photos/id/288/768/768",
            availablePlaces: 0,
            totalPlaces: 12,
            rating: 4.2,
            totalVotes: 20
        },{
            id: 2,
            name: "American Classic",
            destination: "New York",
            country:"USA",
            dateStart: new Date(2021, 4, 4),
            dateEnd: new Date(2021, 4, 24),
            price: 3000,
            description:"For most, any trip to the Empire State starts or finishes in its iconic metropolis: New York City. However, if you confine your travels only to the five boroughs there's a considerable amount you're missing out on.",
            image: "https://picsum.photos/id/376/768/768",
            availablePlaces: 11,
            totalPlaces: 20,
            rating: 3.0,
            totalVotes: 15
        },{
            id: 3,
            name: "Explore San Francisco",
            destination: "San Francisco",
            country:"USA",
            dateStart: new Date(2021, 7, 8),
            dateEnd: new Date(2021, 7, 14),
            price: 2000,
            description:"Grab your coat and a handful of glitter, and enter a wonderland of fog and fabulousness. So long, inhibitions; hello, San Francisco!",
            image: "https://picsum.photos/id/392/768/768",
            availablePlaces: 3,
            totalPlaces: 20,
            rating: 4.3,
            totalVotes: 80
        },{
            id: 4,
            name: "Adventure in Portugal",
            destination: "Lisbon",
            country:"Portugal",
            dateStart: new Date(2021, 9, 14),
            dateEnd: new Date(2021, 9, 28),
            price: 1400,
            description:"Seven cinematic hillsides overlooking the Rio Tejo cradle Lisbon's postcard-perfect panorama of cobbled alleyways, ancient ruins and white-domed cathedrals – a captivating scene crafted over centuries.",
            image: "https://picsum.photos/id/419/768/768",
            availablePlaces: 17,
            totalPlaces: 18,
            rating: 2.0,
            totalVotes: 14
        },{
            id: 5,
            name: "Fabulous Tour",
            destination: "Pisa",
            country:"Italy",
            dateStart: new Date(2021, 5, 2),
            dateEnd: new Date(2021, 5, 11),
            price: 1500,
            description:"Once a maritime power to rival Genoa and Venice, modern Pisa is best known for an architectural project gone terribly wrong. But the world-famous Leaning Tower is just one of many noteworthy sights in this compelling city.",
            image: "https://picsum.photos/id/629/768/768",
            availablePlaces: 17,
            totalPlaces: 18,
            rating: 4.8,
            totalVotes: 30
        }
    ];
